FROM amazonlinux
WORKDIR /opt
RUN yum update -y && yum install git -y && amazon-linux-extras install java-openjdk11 && yum install maven -y
RUN yum install tree -y && git clone https://github.com/ElevenDevOps/test_maven_repo.git && cd test_maven_repo && mvn clean package && ls -lrt target

#below FROM instruction will set new base image & discards old base image(amazonlinux) but all above installations git,maven etc.. will be carried to new tomme base images
FROM tomee
COPY --from=0  /opt/test_maven_repo/target/maven-web-application.war /usr/local/tomee/webapps/
EXPOSE 8080
